export const GET_SINGLE_INVENTORY_REQUEST = "GET_SINGLE_INVENTORY_REQUEST";
export const GET_SINGLE_INVENTORY_SUCCESS = "GET_SINGLE_INVENTORY_SUCCESS";
export const GET_SINGLE_INVENTORY_ERROR = "GET_SINGLE_INVENTORY_ERROR";